arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
synthetic-package: false
header: "// ignore_for_file: non_constant_identifier_names"
format: true
untranslated-messages-file: i18n_missing.txt