name: klimo
description: A new Flutter application.

publish_to: "none"

version: 3.1.1+248

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  android_intent_plus: ^3.1.1
  app_settings: ^5.0.0
  bloc: ^8.1.0
  built_collection: ^5.1.1
  built_value: ^8.4.2
  cached_network_image: ^3.2.1
  cloud_firestore: ^4.0.5
  cloud_functions: ^4.0.4
  collection: ^1.16.0
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.3
  dots_indicator: ^2.1.0
  dotted_border: ^2.0.0+2
  equatable: ^2.0.3
  firebase_analytics: ^10.0.5
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  firebase_crashlytics: ^3.0.5
  firebase_dynamic_links: ^5.0.10
  firebase_in_app_messaging: ^0.7.0+5
  firebase_installations: ^16.3.6
  firebase_messaging: ^14.1.0
  firebase_storage: ^11.0.5
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_cache_manager: ^3.3.0
  flutter_html: ^3.0.0-alpha.3
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10+2
  flutter_signin_button: ^2.0.0
  flutter_svg: ^1.1.1
  font_awesome_flutter: ^9.0.0
  freezed_annotation: ^2.4.1
  google_fonts: ^4.0.4
  google_sign_in: ^5.3.3
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: any
  json_annotation: ^4.8.1
  klimo_datamodels:
    path: ./packages/datamodels
  package_info_plus: ^3.0.2
  path: ^1.8.1
  percent_indicator: ^4.2.3
  provider: ^6.0.4
  scrollable_positioned_list: ^0.3.5
  share_plus: ^7.1.0
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  sign_in_with_apple: ^4.0.0
  url_launcher: ^6.1.4
  uuid: ^3.0.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.jpg"

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/adventcalendar/
    - assets/icons/
    - assets/icons/klimo/
    - assets/logos/
