// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_klimo_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcXC3Xb6f8jkhZRDkMlnV38c0uEaMKvOE',
    appId: '1:1033066123690:android:c87574953d3df9ec511bd3',
    messagingSenderId: '1033066123690',
    projectId: 'klimo-58d29',
    storageBucket: 'klimo-58d29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJsKyr9TnzA9h0Ll5M8TOnhUr4VI38GHU',
    appId: '1:1033066123690:ios:43551d79e4e3af29511bd3',
    messagingSenderId: '1033066123690',
    projectId: 'klimo-58d29',
    storageBucket: 'klimo-58d29.appspot.com',
    androidClientId: '1033066123690-1kis1ki8pfhm65k6osorpbo43g9k56ql.apps.googleusercontent.com',
    iosClientId: '1033066123690-9ibrfgl4766sg8mu6g6dpfp0gn99tv94.apps.googleusercontent.com',
    iosBundleId: 'app.klimo',
  );
}
